import { AppError } from "../../../shared/errors/AppError"
import { IRentalsRepository } from "../repositories/IRentalsRepository"

interface IRequest {
    user_id: string;
    car_id: string;
    expected_return_date: Date;
}

class CreateRentalUseCase {

    constructor(
        private rentalRepository: IRentalsRepository
    ){}

    async execute({user_id, car_id, expected_return_date}: IRequest): Promise<void>{
        const carUnavailable = await this.rentalRepository.findOpenRentalByCar(car_id)

        if(carUnavailable){
            throw new AppError('Car is unavailable')
        }

        const rentalOpenToUser = await this.rentalRepository.findOpenRentalByUser(user_id)

        if(rentalOpenToUser){
            throw new AppError('Theres a rental in progress for user')
        }

    }
}

export  { CreateRentalUseCase } 